
CREATE TABLE IF NOT EXISTS `users` (
	`userID` BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
	`username` VARCHAR(32) NOT NULL,
	`password` VARCHAR(64) NOT NULL, 
	`firstname` VARCHAR(32) NOT NULL, 
	`lastname` VARCHAR(32) NOT NULL, 
	`deleted` ENUM('0','1') DEFAULT '0' NOT NULL, 
	`blocked` ENUM('0','1') DEFAULT '0' NOT NULL, 
	`loginToken` VARCHAR(64) NOT NULL, 
	`dateAdded` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	UNIQUE KEY (`username`)
);

CREATE TABLE IF NOT EXISTS `phone` (
	`phoneID` BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
	`userID` BIGINT NOT NULL, 
	`phone` VARCHAR(16) NOT NULL, 
	`phoneVerified` ENUM('0','1') DEFAULT '0' NOT NULL, 
	`dateAdded` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	UNIQUE KEY (`phone`)
);

CREATE TABLE IF NOT EXISTS `email` (
	`emailID` BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
	`userID` BIGINT NOT NULL, 
	`email` VARCHAR(32) NOT NULL, 
	`emailVerified` ENUM('0','1') DEFAULT '0' NOT NULL, 
	`dateAdded` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	UNIQUE KEY (`email`)
);